FROM amazoncorretto:21 AS build

WORKDIR /account-service

COPY account-service .

RUN ./gradlew bootJar


FROM amazoncorretto:21

WORKDIR /app

COPY --from=build /account-service/app/build/libs/app-*.jar app.jar

EXPOSE 8080/tcp

CMD ["java", "-jar", "app.jar"]
